project:
  type: book

book:
  title: "R Project Zulip Guide"
  author: "R Contribution Working Group"
  date: "7/30/2026"
  chapters:
    - index.qmd
    - intro.qmd

format:
  html: default
  pdf:
    documentclass: scrreprt



